# Generated by Django 5.2.1 on 2025-05-11 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Meat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('price', models.IntegerField(default=0)),
                ('numeration', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField()),
                ('amount_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('AV', 'Available'), ('NV', 'Not Available')], default='AV', max_length=2)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('body', models.TextField(blank=True, null=True)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('sold_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meats', to='base.category')),
            ],
        ),
    ]
