# Generated by Django 5.2.1 on 2025-05-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Main_category',
        ),
        migrations.AlterModelTable(
            name='meat',
            table='Main_meat',
        ),
    ]
